### ISSUE TITLE
Support .onion and .i2p domains

### ISSUE THREAD

**Issue by CutestNekoAqua** [lysand-org/lysand#11]
## The issue

On AP we already have instances running with tor and i2p access, but they still require a normal domain to be able to be federated with, I think it makes sense for us to support hosting Tor and I2P only nodes, so that journalists and others can have a completly anonymous surfing experience. That might be a optional feature.

## Alternatives

We can also just go the AP route and provide tutorials on how to provide I2P access to the already hosted webbed site, but I think thats only if the feature isnt feasible.

## Additional context

People tell me I like to do featurecreep

## Are you willing to work on this feature?

Sure

**Comment by CPlusPatch** [comment]
I think this already works, you should be able to just set base_url inside the config file to any kind of HTTP address, including `i2p` or `tor`!

I don't think that the `fetch` API supports I2P or Tor, so inbound federation probably won't work with other I2P/Tor servers, but outbound should definitely be okay.

This needs testing, @CutestNekoAqua would you be able to set up a Lysand server on localhost and proxy it through I2P/Tor? I am available for any help regarding setup

**Comment by CPlusPatch** [comment]
Here's the relevant config line: (https://github.com/lysand-org/lysand/blob/main/config/config.example.toml)

```toml
[http]
# The full URL Lysand will be reachable by (paths are not supported)
base_url = "https://lysand.social"
# Address to bind to
bind = "0.0.0.0"
bind_port = "8080"
```

You could set it to something like

```toml
[http]
# The full URL Lysand will be reachable by (paths are not supported)
base_url = "https://onionaddress.onion"
# Address to bind to
bind = "0.0.0.0"
bind_port = "8080"
```
